---
title: "data_wrangling_ii"
output: github_document
date: "`r Sys.Date()`"
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```


```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
nsduh_html = read_html(nsduh_url)

```

```{r}
marj_use_df = 
  nsduh_html |>
  html_table() |>
  first() |>
  slice(-1)
```


Import star wars ...

```{r}
swm_html = read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
swm_title_vec = 
  swm_html |>
  html_elements(".lister-item-header a") |>
  html_text()

gross_rev_vec = 
  swm_html |>
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |>
  html_text()

swm_df = 
  tibble(
    title = swm_title_vec,
    gross_rev = gross_rev_vec
  )

```


## APIs

Get water data from NYC

```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |>
  content("parsed")
```

BRFSS Data

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |>
  content()
```


Try it now!

```{r}
poke_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |>
  content()
```















